use_frameworks!

platform :ios, '15.0'

target 'SwiftlyLoader_Example' do
  pod 'SwiftlyLoader', :path => '../'
  pod 'lottie-ios', '~> 4.2.0'

  target 'SwiftlyLoader_Tests' do
    inherit! :search_paths

    
  end
end
